### ISSUE TITLE
P2P Stubs update according to specs change

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-protostubs#5]
According to implementation feedback some changes were done in the specs:

The Configuration json object received as input by the P2P Requester constructor, has a new field `remoteRuntimeURL` containing the RuntimeURL of the remote P2P Handler Stub.

In addition, the P2P Handler Stub should also [fire a new event](https://github.com/reTHINK-project/specs/blob/master/messages/p2p-connection-messages.md#new-p2p-connection-event) as soon as it receives an invitation from a remote P2P Requester containing in the body.

Updated specs [here](https://github.com/reTHINK-project/specs/blob/master/dynamic-view/basics/p2p-setup.md).

**Comment by pchainho** [comment]
As discussed in Slack, the P2P Handler Stub should retrieve the remote runtime URL from the initial data provided by the p2p requester

**Comment by sdruesedow** [comment]
done and pushed to master branch.
P2PRequesterStub now adds a "runtimeURL" attribute to the initial DataObject
