### ISSUE TITLE
Strava protostub

### ISSUE THREAD

**Issue by Felgueiras** [reTHINK-project/dev-protostubs#76]
Very similar to GoogleProtoStub, UserActivityObserver hyperty is responsible for loading the correct protostub, [depending on the OS](https://github.com/reTHINK-project/dev-hyperty/blob/develop/examples/user-activity/UserActivityObserver.js#L24-L31):
- Android: GoogleProtoStub (also for Windows?)
- iOS: StravaProtoStub

To avoid code duplication, a [FitnessProtostub ](https://github.com/reTHINK-project/dev-protostubs/blob/develop/src/protostub/fitness/FitnessProtoStub.js)is to be created.

**Comment by Felgueiras** [comment]
**IDP proxy**

Since a Strava application can only have a single Authorization Callback Domain, [clientID must be changed according to the domain/app](https://github.com/reTHINK-project/dev-protostubs/blob/develop/src/idpproxy/strava/StravaInfo.js#L8).

**Comment by pchainho** [comment]
it seems Authorisation is requested everytime the token expires. Check if the access token is well stored and retrieved
